package linkedlist.linkedlist;

public class Program {
	public static void main(String[] args) {
		LinkedList<Integer> ll = new LinkedList<>();
		
		System.out.println("Linked List");
		System.out.println();
		System.out.println(ll);
		System.out.println("First element in List: " + ll.peekFirst());
		System.out.println("Last element in List: " + ll.peekLast());
		System.out.println("Size: " + ll.getSize());
		System.out.println();
		ll.addFirst(1);
		System.out.println(ll);
		System.out.println("First element in List: " + ll.peekFirst());
		System.out.println("Last element in List: " + ll.peekLast());
		System.out.println("Size: " + ll.getSize());
		System.out.println();
		ll.addFirst(9);
		System.out.println(ll);
		System.out.println("First element in List: " + ll.peekFirst());
		System.out.println("Last element in List: " + ll.peekLast());
		System.out.println("Size: " + ll.getSize());
		System.out.println();
		ll.addFirst(7);
		System.out.println(ll);
		System.out.println("First element in List: " + ll.peekFirst());
		System.out.println("Last element in List: " + ll.peekLast());
		System.out.println("Size: " + ll.getSize());
		System.out.println();
		ll.addLast(3);
		System.out.println(ll);
		System.out.println("First element in List: " + ll.peekFirst());
		System.out.println("Last element in List: " + ll.peekLast());
		System.out.println("Size: " + ll.getSize());
		System.out.println();
		ll.addLast(4);
		System.out.println(ll);
		System.out.println("First element in List: " + ll.peekFirst());
		System.out.println("Last element in List: " + ll.peekLast());
		System.out.println("Size: " + ll.getSize());
		
		System.out.println();
		System.out.println("--------------------------");
		System.out.println("Testing Methods:");
		System.out.println(ll);
		System.out.println("get(9): " + ll.get(9));
		System.out.println("get(0): " + ll.get(0));
		System.out.println("get(3): " + ll.get(3));
		System.out.println("indexOf(9): " + ll.indexOf(9));
		System.out.println("indexOf(3): " + ll.indexOf(3));
		System.out.println("indexOf(2): " + ll.indexOf(2));
		System.out.println("--------------------------");
		System.out.println();
		
		System.out.println("Removing element: " + ll.removeLast());
		System.out.println(ll);
		System.out.println("First element in List: " + ll.peekFirst());
		System.out.println("Last element in List: " + ll.peekLast());
		System.out.println("Size: " + ll.getSize());
		System.out.println();
		System.out.println("Removing element: " + ll.removeFirst());
		System.out.println(ll);
		System.out.println("First element in List: " + ll.peekFirst());
		System.out.println("Last element in List: " + ll.peekLast());
		System.out.println("Size: " + ll.getSize());
		System.out.println();
		System.out.println("Removing element: " + ll.removeLast());
		System.out.println(ll);
		System.out.println("First element in List: " + ll.peekFirst());
		System.out.println("Last element in List: " + ll.peekLast());
		System.out.println("Size: " + ll.getSize());
		System.out.println();
		System.out.println("Removing element: " + ll.removeFirst());
		System.out.println(ll);
		System.out.println("First element in List: " + ll.peekFirst());
		System.out.println("Last element in List: " + ll.peekLast());
		System.out.println("Size: " + ll.getSize());
		System.out.println();
		System.out.println("Removing element: " + ll.removeLast());
		System.out.println(ll);
		System.out.println("First element in List: " + ll.peekFirst());
		System.out.println("Last element in List: " + ll.peekLast());
		System.out.println("Size: " + ll.getSize());
		
		System.out.println();
		System.out.println();
		System.out.println();
		System.out.println("Linked List 2");
		System.out.println();
		LinkedList<Integer> ll2 = new LinkedList<>();
		
		System.out.println(ll2);
		System.out.println("First element in List: " + ll2.peekFirst());
		System.out.println("Last element in List: " + ll2.peekLast());
		System.out.println("Size: " + ll2.getSize());
		System.out.println();
		ll2.add(0, 1);
		System.out.println(ll2);
		System.out.println("First element in List: " + ll2.peekFirst());
		System.out.println("Last element in List: " + ll2.peekLast());
		System.out.println("Size: " + ll2.getSize());
		System.out.println();
		ll2.add(1, 9);
		System.out.println(ll2);
		System.out.println("First element in List: " + ll2.peekFirst());
		System.out.println("Last element in List: " + ll2.peekLast());
		System.out.println("Size: " + ll2.getSize());
		System.out.println();
		ll2.addFirst(7);
		System.out.println(ll2);
		System.out.println("First element in List: " + ll2.peekFirst());
		System.out.println("Last element in List: " + ll2.peekLast());
		System.out.println("Size: " + ll2.getSize());
		System.out.println();
		ll2.addLast(3);
		System.out.println(ll2);
		System.out.println("First element in List: " + ll2.peekFirst());
		System.out.println("Last element in List: " + ll2.peekLast());
		System.out.println("Size: " + ll2.getSize());
		System.out.println();
		ll2.add(2, 4);
		System.out.println(ll2);
		System.out.println("First element in List: " + ll2.peekFirst());
		System.out.println("Last element in List: " + ll2.peekLast());
		System.out.println("Size: " + ll2.getSize());
		
		System.out.println();
		System.out.println("--------------------------");
		System.out.println("Testing Methods:");
		System.out.println(ll2);
		System.out.println("get(9): " + ll2.get(9));
		System.out.println("get(0): " + ll2.get(0));
		System.out.println("get(3): " + ll2.get(3));
		System.out.println("indexOf(9): " + ll2.indexOf(9));
		System.out.println("indexOf(3): " + ll2.indexOf(3));
		System.out.println("indexOf(2): " + ll2.indexOf(2));
		System.out.println("--------------------------");
		System.out.println();
		
		System.out.println("Removing element: " + ll2.remove(2));
		System.out.println(ll2);
		System.out.println("First element in List: " + ll2.peekFirst());
		System.out.println("Last element in List: " + ll2.peekLast());
		System.out.println("Size: " + ll2.getSize());
		System.out.println();
		System.out.println("Removing element: " + ll2.remove(3));
		System.out.println(ll2);
		System.out.println("First element in List: " + ll2.peekFirst());
		System.out.println("Last element in List: " + ll2.peekLast());
		System.out.println("Size: " + ll2.getSize());
		System.out.println();
		System.out.println("Removing element: " + ll2.remove(0));
		System.out.println(ll2);
		System.out.println("First element in List: " + ll2.peekFirst());
		System.out.println("Last element in List: " + ll2.peekLast());
		System.out.println("Size: " + ll2.getSize());
		System.out.println();
		System.out.println("Removing element: " + ll2.removeFirst());
		System.out.println(ll2);
		System.out.println("First element in List: " + ll2.peekFirst());
		System.out.println("Last element in List: " + ll2.peekLast());
		System.out.println("Size: " + ll2.getSize());
		System.out.println();
		System.out.println("Removing element: " + ll2.removeLast());
		System.out.println(ll2);
		System.out.println("First element in List: " + ll2.peekFirst());
		System.out.println("Last element in List: " + ll2.peekLast());
		System.out.println("Size: " + ll2.getSize());
	}
}
